name: Typescript CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: serverless_weather_api

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Make .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SOME_API_KEY_GEO_KEY: ${{ secrets.GEO_KEY }}
          envkey_SOME_API_KEY_WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          directory: './'
          file_name: '.env'
          fail_on_empty: true
      - run: npm ci
      - run: npm run systemTest
      - run: npm run deploy