name: Typescript CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GEO_KEY: ${{ secrets.GEO_KEY }}
  WEATHER_KEY: ${{ secrets.WEATHER_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: create .env file
        run: |
          touch .env
          echo $GEO_KEY >> .env
          echo $WEATHER_KEY >> .env
      - run: npm run systemTest
      - run: npm run deploy